---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@9.0.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - almalinux-8
          - almalinux-9
          - almalinux-10
          - amazonlinux-2023
          - centos-stream-9
          - centos-stream-10
          - debian-12
          - debian-13
          - oraclelinux-8
          - oraclelinux-9
          - rockylinux-8
          - rockylinux-9
          - rockylinux-10
          - ubuntu-2204
          - ubuntu-2404
        suite:
          - default
          - client-80
          - client-84
          - devel-80
          - devel-84
          - server-80
          - server-84
          - source-80
          - source-84
          - cluster-80
          - cluster-84
          - replication-80
          - replication-84
          - resources-80
          - resources-84
        exclude:
          - os: almalinux-10
            suite: client-80
          - os: almalinux-10
            suite: devel-80
          - os: almalinux-10
            suite: server-80
          - os: almalinux-10
            suite: source-80
          - os: almalinux-10
            suite: cluster-80
          - os: almalinux-10
            suite: replication-80
          - os: almalinux-10
            suite: resources-80
          - os: centos-stream-10
            suite: client-80
          - os: centos-stream-10
            suite: devel-80
          - os: centos-stream-10
            suite: server-80
          - os: centos-stream-10
            suite: source-80
          - os: centos-stream-10
            suite: replication-80
          - os: centos-stream-10
            suite: resources-80
          - os: centos-stream-10
            suite: cluster-80
          - os: debian-13
            suite: client-80
          - os: debian-13
            suite: devel-80
          - os: debian-13
            suite: server-80
          - os: debian-13
            suite: source-80
          - os: debian-13
            suite: cluster-80
          - os: debian-13
            suite: replication-80
          - os: debian-13
            suite: resources-80
          - os: rockylinux-10
            suite: client-80
          - os: rockylinux-10
            suite: devel-80
          - os: rockylinux-10
            suite: server-80
          - os: rockylinux-10
            suite: source-80
          - os: rockylinux-10
            suite: cluster-80
          - os: rockylinux-10
            suite: replication-80
          - os: rockylinux-10
            suite: resources-80
          - os: debian-12
            suite: devel-84
          - os: debian-13
            suite: devel-84
          - os: ubuntu-2204
            suite: devel-84
          - os: ubuntu-2404
            suite: devel-84
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install Chef
        uses: sous-chefs/.github/.github/actions/install-workstation@9.0.0
      - name: Install Policyfile
        run: chef install Policyfile.rb
      # https://github.com/actions/virtual-environments/issues/181#issuecomment-610874237
      - name: Disable apparmor for mysqld
        run: |
          set -x
          sudo apt-get -y remove mysql-server --purge
          sudo apt-get -y install apparmor-profiles
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
          set -x
          sudo journalctl -l --since today
          sudo docker version
          sudo docker info
          KITCHEN_LOCAL_YAML=kitchen.dokken.yml /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"
